version: "3"

services:
  adminer:
    image: adminer:4.8.1
    environment:
      VIRTUAL_HOST: adminer.test

  whoami:
    image: jwilder/whoami
    environment:
      VIRTUAL_HOST: whoami.test

  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    